name: "WebApp-Updater"
version: 0.1.11
slug: webapp_updater
description: "Aktualisiert lokale WebApps aus GitHub, protokolliert Updates und öffnet WebApps direkt im Browser."
image: ghcr.io/parrrrd/home-assistant-webapps/webapp-updater

arch:
  - amd64
  - aarch64

startup: services
boot: auto
init: false

hassio_api: true
homeassistant_api: true
hassio_role: manager

map:
  - type: addons
    read_only: false

options:
  check_interval_minutes: 1
  check_interval_seconds: 20
  auto_apply_updates: true

schema:
  check_interval_minutes: int(1,1440)
  check_interval_seconds: int(15,3600)
  auto_apply_updates: bool
