name: Kicktipp Bot für Katharina
version: 0.1.8
slug: kicktipp_tipbot2
description: Kicktipp Bot für Katharina
url: https://github.com/Parrrrd/home-assistant-webapps
image: ghcr.io/parrrrd/home-assistant-webapps/kicktipp_tipbot2-private
arch:
  - amd64
startup: services
boot: manual
init: false
webui: "http://[HOST]:[PORT:8149]/"
map:
  - share:rw
  - config:rw
ports:
  8149/tcp: 8149
ports_description:
  8149/tcp: Weboberfläche
options:
  tipprunde: ""
  username: ""
  password: ""
  auto_save_default: true
  kicktipp_url: ""
schema:
  tipprunde: str
  username: str
  password: password
  auto_save_default: bool
  kicktipp_url: str
