name: center_parcs_preisueberwachung

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: center_parcs_preisueberwachung-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-addon-build.yml
    with:
      app_directory: center_parcs_preisueberwachung
      architectures: '["aarch64", "amd64"]'
      image_name: center_parcs_preisueberwachung
      publish: ${{ inputs.publish }}
    secrets: inherit
