name: center_parcs_preisueberwachung

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: center_parcs_preisueberwachung-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-addon-build.yml
