name: inventurmanager

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: inventurmanager-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-addon-build.yml
    with:
      app_directory: inventurmanager
      architectures: '["aarch64", "amd64", "armv7", "armhf", "i386"]'
      image_name: inventurmanager
      publish: ${{ inputs.publish }}
    secrets: inherit
