name: jarvis_ai

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: jarvis_ai-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-addon-build.yml
    with:
      app_directory: jarvis_ai
      architectures: '["amd64"]'
      image_name: jarvis_ai
      publish: ${{ inputs.publish }}
    secrets: inherit
