name: kicktipp_tipbot2

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: kicktipp_tipbot2-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-addon-build.yml
    with:
      app_directory: kicktipp_tipbot2
      architectures: '["amd64"]'
      image_name: kicktipp_tipbot2
      publish: ${{ inputs.publish }}
    secrets: inherit
