name: mova_protokoll

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: mova_protokoll-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-addon-build.yml
    with:
      app_directory: mova_protokoll
      architectures: '["aarch64", "amd64", "armhf", "armv7", "i386"]'
      image_name: mova_protokoll
      publish: ${{ inputs.publish }}
    secrets: inherit
