name: serienplaner

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: serienplaner-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-addon-build.yml
    with:
      app_directory: serienplaner
      architectures: '["amd64"]'
      image_name: serienplaner
      publish: ${{ inputs.publish }}
    secrets: inherit
