name: webapp_uebersicht

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: webapp_uebersicht-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-addon-build.yml
    with:
      app_directory: webapp_uebersicht
      architectures: '["amd64", "aarch64"]'
      image_name: webapp_uebersicht
      publish: ${{ inputs.publish }}
    secrets: inherit
