name: webapp_sync_manager

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Image veröffentlichen
        required: true
        type: boolean
        default: false

permissions: {}

concurrency:
  group: webapp_sync_manager-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-addon-build.yml
    with:
      app_directory: webapp_sync_manager
      architectures: '["amd64"]'
      image_name: webapp_sync_manager
      publish: ${{ inputs.publish }}
    secrets: inherit
